export const RESOURCE_SERVER_ADDRESS = 'https://localhost:44305/';

export const LOAD_SUBSCRIPTIONS_START = 'redux-oidc-sample/LOAD_SUBSCRIPTIONS_START';
export const LOAD_SUBSCRIPTIONS_SUCCESS = 'redux-oidc-sample/LOAD_SUBSCRIPTIONS_SUCCESS';

export const LOAD_TEST_RESOURCE_START = 'redux-oidc-sample/LOAD_TEST_RESOURCE_START';
export const LOAD_TEST_RESOURCE_SUCCESS = 'redux-oidc-sample/LOAD_TEST_RESOURCE_SUCCESS';

export const LOAD_PROFILE_RESOURCE_START = 'redux-oidc-sample/LOAD_PROFILE_RESOURCE_START';
export const LOAD_PROFILE_RESOURCE_SUCCESS = 'redux-oidc-sample/LOAD_PROFILE_RESOURCE_SUCCESS';

export const UPDATE_PROFILE_RESOURCE_START = 'redux-oidc-sample/UPDATE_PROFILE_RESOURCE_START';
export const UPDATE_PROFILE_RESOURCE_SUCCESS = 'redux-oidc-sample/UPDATE_PROFILE_RESOURCE_SUCCESS';

export const LOAD_GROUP_DETAILS_START = 'redux-oidc-sample/LOAD_GROUP_DETAILS_START';
export const LOAD_GROUP_DETAILS_SUCCESS = 'redux-oidc-sample/LOAD_GROUP_DETAILS_SUCCESS';
