export const LOAD_SUBSCRIPTIONS_START = 'redux-oidc-sample/LOAD_SUBSCRIPTIONS_START';
export const LOAD_SUBSCRIPTIONS_SUCCESS = 'redux-oidc-sample/LOAD_SUBSCRIPTIONS_SUCCESS';

export const LOAD_TEST_RESOURCE_START = 'redux-oidc-sample/LOAD_TEST_RESOURCE_START';
export const LOAD_TEST_RESOURCE_SUCCESS = 'redux-oidc-sample/LOAD_TEST_RESOURCE_SUCCESS';
